language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CONFIGURE_OPTIONS='--with-threads=pthread'
  - CONFIGURE_OPTIONS='--with-threads=fork'
  - CONFIGURE_OPTIONS='--with-threads=ucontext'
  - CONFIGURE_OPTIONS='--disable-ipv6 --disable-fips --disable-systemd --disable-libwrap'

before_install:
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get update -qq; sudo apt-get install -y libssl-dev libwrap0-dev; fi

before_script: autoreconf -fvi && touch src/dhparam.c

script: ./configure $CONFIGURE_OPTIONS && make && make test
