language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libssl-dev libwrap0-dev libsystemd-dev
  - autoreconf -fvi && ./configure
script: make
